version: "2"

services:
 minetest:
  image: registry.rudin.io/x86/minetest:0.4.17.1
  restart: always
  ports:
   - "30003:30000/udp"
  depends_on:
   - "postgres"
  volumes:
   - "./minetest:/data"
  command: minetestserver --config /data/minetest.conf --world /data/world/ --quiet

 postgres:
  image: postgres
  restart: always
  environment:
   POSTGRES_PASSWORD: enter
  volumes:
   - "./postgres:/var/lib/postgresql/data"

# tileserver:
#  image: registry.rudin.io/x86/minetest-tileserver
#  restart: always
#  ports:
#   - "8080:8080"
#  depends_on:
#   - "postgres"
#  volumes:
#   - "./data/tileserver.properties:/tileserver.properties"
#   - "./data/tiles:/tiles"
#  logging:
#   options:
#    max-size: 50m

