version: "2"



services:
 minetest:
  image: registry.rudin.io/x86/minetest:pandorabox
  restart: always
  ports:
   - "30000:30000/udp"
  depends_on:
   - "postgres"
  volumes:
   - "./data/minetest:/data"
   - "./data/minetest/debug.txt:/root/.minetest/debug.txt"
  working_dir: /data
  command: minetestserver --config /data/minetest.conf --world /data/world/ --quiet
  logging:
   options:
    max-size: 50m

 postgres:
  image: postgres:10
  restart: always
  shm_size: '2gb'
  environment:
   POSTGRES_PASSWORD: enter
  volumes:
   - "./data/postgres-minetest:/var/lib/postgresql/data"
  logging:
   options:
    max-size: 50m

 webhook:
  image: registry.rudin.io/x86/webhook-git-updater
  restart: always

 geoip:
  image: klauspost/geoip-service
  restart: always
  volumes:
   - "./data/GeoLite2-City.mmdb:/data/geodb.mmdb"

 auth-proxy:
  image: registry.rudin.io/x86/mt-auth-proxy:latest
  restart: always

 beerchat-proxy:
  image: registry.rudin.io/x86/beerchat_proxy:latest
  restart: always
  environment:
   IRC_HOST: chat.freenode.net
   IRC_CHANNEL: pandorabox
   IRC_USERNAME: pandorabot

 mapserver:
  image: registry.rudin.io/x86/mapserver
  restart: always
  networks:
   - default
  depends_on:
   - "postgres"
  volumes:
   - "./data/minetest/world:/minetest"
  working_dir: "/minetest"
  logging:
   options:
    max-size: 50m

 wiki:
  image: registry.rudin.io/x86/php-pandorabox
  restart: always
  volumes:
   - "./data/wiki:/var/www/html/wiki"
  logging:
   options:
    max-size: 50m

 portainer:
  image: portainer/portainer
  restart: always
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /opt/portainer/data:/data


 nginx:
  image: nginx
  networks:
   - terminator
   - default
  restart: always
  depends_on:
   - highscore
   - grafana
   - mapserver
   - webmail
   - webhook
   - portainer
  environment:
   VIRTUAL_PORT: 80
   VIRTUAL_HOST: pandorabox.io
   LETSENCRYPT_HOST: pandorabox.io
   LETSENCRYPT_EMAIL: thomas@rudin.io
  volumes:
   - "./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
   - "./data/nginx/routes:/routes"
   - "./data/nginx/html:/html"
   - "./data/minetest/world/news.txt:/html/news.txt"
  logging:
   options:
    max-size: 50m

 highscore:
  image: registry.rudin.io/x86/minetest-xp-highscore
  restart: always
  volumes:
   - "./data/minetest/world:/data/world:ro"
  depends_on:
   - postgres
  environment:
   PGHOST: postgres
   PGUSER: postgres
   PGDATABASE: postgres
   PGPASSWORD: enter
   PGPORT: 5432

 webmail:
  image: registry.rudin.io/x86/minetest-webmail
  restart: always
  depends_on:
   - minetest

 pushgateway:
  image: prom/pushgateway
  restart: always

 postgres-exporter:
  image: wrouesnel/postgres_exporter
  restart: always
  depends_on:
   - "postgres"
  environment:
   DATA_SOURCE_NAME: postgresql://postgres:enter@postgres:5432/?sslmode=disable
  logging:
   options:
    max-size: 50m

 prometheus:
  image: prom/prometheus:v2.11.1
  volumes:
   - ./data/prometheus.yml:/etc/prometheus/prometheus.yml
   - ./data/prometheus:/prometheus
  depends_on:
   - "pushgateway"
  command:
   - "--config.file=/etc/prometheus/prometheus.yml"
   - "--storage.tsdb.retention.time=2d"
  logging:
   options:
    max-size: 50m

 grafana:
  image: grafana/grafana
  restart: always
  environment:
   - GF_SECURITY_ADMIN_PASSWORD=enter
  depends_on:
   - prometheus
  volumes:
   - "./data/grafana:/var/lib/grafana"
   - "./data/grafana.ini:/etc/grafana/grafana.ini"
  logging:
   options:
    max-size: 50m

 kv:
  image: anapsix/webdis
  restart: always
  environment:
   - LOCAL_REDIS=true

networks:
 terminator:
  external: true

 
