version: "2"

services:
 minetest:
  image: registry.rudin.io/x86/minetest:backport-0.4
  restart: always
  ports:
   - "30000:30000/udp"
  depends_on:
   - "postgres"
  volumes:
   - "./minetest:/data"
  command: minetestserver --config /data/minetest.conf --world /data/world/ --quiet

 tileserver:
  image: registry.rudin.io/x86/minetest-tileserver
  restart: always
  networks:
   - default
   - terminator
  depends_on:
   - "postgres"
  volumes:
   - "./tileserver.properties:/tileserver.properties"
  environment:
   VIRTUAL_PORT: 8080
   VIRTUAL_HOST: pandorabox.io
   LETSENCRYPT_HOST: pandorabox.io

 postgres:
  image: postgres
  restart: always
  environment:
   POSTGRES_PASSWORD: enter
  volumes:
   - "./postgres:/var/lib/postgresql/data"

 postgres-tiles:
  image: postgres
  restart: always
  environment:
   POSTGRES_PASSWORD: enter
  volumes:
   - "./postgres-tiles:/var/lib/postgresql/data"

 forum:
  image: registry.rudin.io/x86/vanilla-forum
  restart: always
  depends_on:
   - "forum-db"
  volumes:
  - "./data/forum-web:/var/www/html"

 forum-db:
  image: mysql:5
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: enter
  volumes:
   - "./data/forum-db:/var/lib/mysql"

networks:
 terminator:
  external: true
