version: "2"



services:
 minetest:
  image: buckaroobanzay/minetest:stable-5-debug
  restart: always
  ports:
   - "30000:30000/udp"
  depends_on:
   - "postgres"
  volumes:
   - "./data/minetest:/data"
   - "./data/crashlogs:/crashlogs"
   - "./data/minetest/debug.txt:/root/.minetest/debug.txt"
  logging:
   options:
    max-size: 50m

 postgres:
  image: postgres:11
  restart: always
  shm_size: '2gb'
  environment:
   POSTGRES_PASSWORD: enter
  volumes:
   - "./data/postgres:/var/lib/postgresql/data"
  command:
   - "postgres"
   - "-c"
   - "shared_buffers=4GB"
   - "-c"
   - "synchronous_commit=off"
  logging:
   options:
    max-size: 50m

 geoip:
  image: klauspost/geoip-service
  restart: always
  volumes:
   - "./data/GeoLite2-City.mmdb:/data/geodb.mmdb"

 auth-proxy:
  image: minetestauth/minetest-auth-proxy
  labels:
    com.centurylinklabs.watchtower.enable: "true"
  restart: always

 beerchat-proxy:
  image: beerchat/beerchat
  volumes:
   - "./data/beerchat.json:/data/beerchat.json:ro"
  labels:
   com.centurylinklabs.watchtower.enable: "true"
  restart: always

 mapserver:
  image: minetestmapserver/mapserver:latest
  restart: always
  labels:
   com.centurylinklabs.watchtower.enable: "true"
  depends_on:
   - "postgres"
  volumes:
   - "./data/minetest/world:/minetest"
  working_dir: "/minetest"
  logging:
   options:
    max-size: 50m

 wiki:
  image: buckaroobanzay/php
  restart: always
  depends_on:
   - "postgres"
  volumes:
   - "./data/wiki:/var/www/html/wiki"
  logging:
   options:
    max-size: 50m

 nginx:
  image: nginx
  networks:
   - terminator
   - default
  restart: always
  depends_on:
   - highscore
   - mapserver
   - webmail
   - wiki
  environment:
   VIRTUAL_PORT: 80
   VIRTUAL_HOST: pandorabox.io
   LETSENCRYPT_HOST: pandorabox.io
   LETSENCRYPT_EMAIL: thomas@rudin.io
  volumes:
   - "./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
   - "./data/nginx/routes:/routes"
   - "./data/nginx/html:/html"
   - "./data/minetest/world/news.txt:/html/news.txt"
   - "./data/crashlogs:/crashlogs"
  logging:
   options:
    max-size: 50m

 highscore:
  image: buckaroobanzay/xphighscore
  restart: always
  labels:
   com.centurylinklabs.watchtower.enable: "true"
  volumes:
   - "./data/minetest/world:/data/world:ro"
  depends_on:
   - postgres
  environment:
   PGHOST: postgres
   PGUSER: postgres
   PGDATABASE: postgres
   PGPASSWORD: enter
   PGPORT: 5432

 webmail:
  image: minetestmail/mail
  restart: always
  labels:
   com.centurylinklabs.watchtower.enable: "true"
  depends_on:
   - minetest

 manager:
  image: buckaroobanzay/minetest_manager
  restart: always
  volumes:
   - "./data:/data"
  environment:
   - WORLDMODS_DIR=/data/minetest/world/worldmods
   - WORLDMODS_BRANCH=master
   - MEDIADIR=/data/nginx/html/media
   - DEBUG_LOG=/data/minetest/debug.txt
   - ERROR_LOG_OUTPUT=/data/nginx/html/error-log.txt
  logging:
   options:
    max-size: 50m

 kv:
  image: anapsix/webdis
  restart: always
  environment:
   - LOCAL_REDIS=true

networks:
 terminator:
  external: true

 
