version: "2"



services:
 minetest:
  image: registry.rudin.io/x86/minetest:0.4.17.1
  restart: always
  ports:
   - "30000:30000/udp"
  depends_on:
   - "postgres"
  volumes:
   - "./data/minetest:/data"
  command: minetestserver --config /data/minetest.conf --world /data/world/ --quiet
  logging:
   options:
    max-size: 50m

 tileserver:
  image: registry.rudin.io/x86/minetest-tileserver
  restart: always
  networks:
   - default
  depends_on:
   - "postgres"
   - "postgres-tiles"
  volumes:
   - "./data/tileserver.properties:/tileserver.properties"
   - "./data/tileserver.layers.json:/layers.json"
   - "./data/tiles:/tiles"
  logging:
   options:
    max-size: 50m

 postgres:
  image: postgres:10
  restart: always
  environment:
   POSTGRES_PASSWORD: enter
  volumes:
   - "./data/postgres-minetest:/var/lib/postgresql/data"
   - "./data/postgres-minetest-backup:/backup"
   - "./data/postgres-minetest-restore:/restore"

 postgres-tiles:
  image: postgres
  restart: always
  environment:
   POSTGRES_PASSWORD: enter
  volumes:
   - "./data/postgres-tiles:/var/lib/postgresql/data"

 nginx:
  image: nginx
  networks:
   - terminator
   - default
  restart: always
  environment:
   VIRTUAL_PORT: 80
   VIRTUAL_HOST: pandorabox.io
   LETSENCRYPT_HOST: pandorabox.io
   LETSENCRYPT_EMAIL: thomas@rudin.io
  volumes:
   - "./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
   - "./data/nginx/routes:/routes"
   - "./data/nginx/html:/html"
  logging:
   options:
    max-size: 50m

 highscore:
  image: registry.rudin.io/x86/minetest-xp-highscore
  restart: always
  volumes:
   - "./data/minetest/world/ranks.json:/data/public/js/ranks.json:ro"
  environment:
   PGHOST: postgres
   PGUSER: postgres
   PGDATABASE: postgres
   PGPASSWORD: enter
   PGPORT: 5432

 wiki:
  image: registry.rudin.io/x86/php-pandorabox
  restart: always
  volumes:
   - "./data/wiki:/var/www/html/wiki"
  logging:
   options:
    max-size: 50m

 forum:
  image: registry.rudin.io/x86/php-pandorabox
  restart: always
  depends_on:
   - "forum-db"
  volumes:
  - "./data/forum-web:/var/www/html"

 forum-db:
  image: mysql:5
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: enter
  volumes:
   - "./data/forum-db:/var/lib/mysql"

 minetest-exporter:
  image: registry.rudin.io/x86/minetest-serverstats-exporter
  restart: always

 node-exporter:
  image: prom/node-exporter
  user: root
  privileged: true
  volumes:
   - /proc:/host/proc:ro
   - /sys:/host/sys:ro
   - /:/rootfs:ro
  command:
   - '--path.procfs=/host/proc'
   - '--path.sysfs=/host/sys'
   - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
  ports:
   - '9100:9100'
  networks:
   - monitor-net
   - default
  logging:
   options:
    max-size: 50m

 postgres-exporter:
  image: wrouesnel/postgres_exporter
  restart: always
  depends_on:
   - "postgres"
  environment:
   DATA_SOURCE_NAME: postgresql://postgres:enter@postgres:5432/?sslmode=disable
  logging:
   options:
    max-size: 50m

 postgres-tiles-exporter:
  image: wrouesnel/postgres_exporter
  restart: always
  depends_on:
   - "postgres-tiles"
  environment:
   DATA_SOURCE_NAME: postgresql://postgres-tiles:enter@postgres:5432/?sslmode=disable
  logging:
   options:
    max-size: 50m

 prometheus:
  image: prom/prometheus:0.18.0
  volumes:
   - ./data/prometheus.yml:/etc/prometheus/prometheus.yml
   - ./data/prometheus:/prometheus/data
  command:
   - '-config.file=/etc/prometheus/prometheus.yml'
  ports:
   - '9090:9090'
  logging:
   options:
    max-size: 50m

 grafana:
  image: grafana/grafana
  environment:
   - GF_SECURITY_ADMIN_PASSWORD=enter
  depends_on:
   - prometheus
  ports:
   - "3000:3000"
  volumes:
   - "./data/grafana:/var/lib/grafana"
   - "./data/grafana.ini:/etc/grafana/grafana.ini"
  logging:
   options:
    max-size: 50m


networks:
 terminator:
  external: true
 monitor-net:
  driver: bridge

 
