version: "2"

services:
 minetest:
  image: registry.rudin.io/x86/minetest:0.4.17
  restart: always
  ports:
   - "30000:30000/udp"
  depends_on:
   - "postgres"
  volumes:
   - "./minetest:/data"
  command: minetestserver --config /data/minetest.conf --world /data/world/ --quiet

 tileserver:
  image: registry.rudin.io/x86/minetest-tileserver
  restart: always
  networks:
   - default
   - terminator
  depends_on:
   - "postgres"
  volumes:
   - "./data/tileserver.properties:/tileserver.properties"

 postgres:
  image: postgres
  restart: always
  environment:
   POSTGRES_PASSWORD: enter
  volumes:
   - "./postgres:/var/lib/postgresql/data"

 postgres-tiles:
  image: postgres
  restart: always
  environment:
   POSTGRES_PASSWORD: enter
  volumes:
   - "./postgres-tiles:/var/lib/postgresql/data"

 nginx:
  image: nginx
  networks:
   - terminator
   - default
  restart: always
  environment:
   VIRTUAL_PORT: 80
   VIRTUAL_HOST: pandorabox.io
   LETSENCRYPT_HOST: pandorabox.io
   LETSENCRYPT_EMAIL: thomas@rudin.io
  volumes:
   - "./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
   - "./data/nginx/routes:/routes"
   - "./data/nginx/html:/html"

 highscore:
  image: registry.rudin.io/x86/minetest-xp-highscore
  restart: always
  environment:
   PGHOST: postgres
   PGUSER: postgres
   PGDATABASE: postgres
   PGPASSWORD: enter
   PGPORT: 5432

 forum:
  image: registry.rudin.io/x86/vanilla-forum
  restart: always
  depends_on:
   - "forum-db"
  volumes:
  - "./data/forum-web:/var/www/html"

 forum-db:
  image: mysql:5
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: enter
  volumes:
   - "./data/forum-db:/var/lib/mysql"

networks:
 terminator:
  external: true
