version: "2"



services:
 minetest:
  image: registry.rudin.io/x86/minetest:latest
  restart: always
  ports:
   - "30000:30000/udp"
  depends_on:
   - "postgres"
  volumes:
   - "./data/minetest:/data"
   - "./data/minetest/debug.txt:/root/.minetest/debug.txt"
  working_dir: /data
  command: minetestserver --config /data/minetest.conf --world /data/world/ --quiet
  logging:
   options:
    max-size: 50m

 postgres:
  image: postgres:11
  restart: always
  shm_size: '2gb'
  environment:
   POSTGRES_PASSWORD: enter
  volumes:
   - "./data/postgres:/var/lib/postgresql/data"
  command:
   - "postgres"
   - "-c"
   - "shared_buffers=4GB"
   - "-c"
   - "synchronous_commit=off"
  logging:
   options:
    max-size: 50m

 geoip:
  image: klauspost/geoip-service
  restart: always
  volumes:
   - "./data/GeoLite2-City.mmdb:/data/geodb.mmdb"

 auth-proxy:
  image: minetestauth/minetest-auth-proxy
  labels:
    com.centurylinklabs.watchtower.enable: "true"
  restart: always

 beerchat-proxy:
  image: beerchat/beerchat
  volumes:
   - "./data/beerchat.json:/data/beerchat.json:ro"
  labels:
    com.centurylinklabs.watchtower.enable: "true"
  restart: always

 mapserver:
  image: minetestmapserver/mapserver:latest
  restart: always
  labels:
   com.centurylinklabs.watchtower.enable: "true"
  depends_on:
   - "postgres"
  volumes:
   - "./data/minetest/world:/minetest"
  working_dir: "/minetest"
  logging:
   options:
    max-size: 50m

 wiki:
  image: buckaroobanzay/php
  restart: always
  depends_on:
   - "postgres"
  volumes:
   - "./data/wiki:/var/www/html/wiki"
  logging:
   options:
    max-size: 50m

 nginx:
  image: nginx
  networks:
   - terminator
   - default
  restart: always
  depends_on:
   - highscore
   - grafana
   - mapserver
   - webmail
   - wiki
  environment:
   VIRTUAL_PORT: 80
   VIRTUAL_HOST: pandorabox.io
   LETSENCRYPT_HOST: pandorabox.io
   LETSENCRYPT_EMAIL: thomas@rudin.io
  volumes:
   - "./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
   - "./data/nginx/routes:/routes"
   - "./data/nginx/html:/html"
   - "./data/minetest/world/news.txt:/html/news.txt"
  logging:
   options:
    max-size: 50m

 highscore:
  image: registry.rudin.io/x86/minetest-xp-highscore
  restart: always
  volumes:
   - "./data/minetest/world:/data/world:ro"
  depends_on:
   - postgres
  environment:
   PGHOST: postgres
   PGUSER: postgres
   PGDATABASE: postgres
   PGPASSWORD: enter
   PGPORT: 5432

 webmail:
  image: minetestmail/mail
  restart: always
  labels:
   com.centurylinklabs.watchtower.enable: "true"
  depends_on:
   - minetest

 pushgateway:
  image: prom/pushgateway
  restart: always

 postgres-exporter:
  image: wrouesnel/postgres_exporter
  restart: always
  depends_on:
   - "postgres"
  environment:
   DATA_SOURCE_NAME: postgresql://postgres:enter@postgres:5432/?sslmode=disable
  logging:
   options:
    max-size: 50m

 prometheus:
  image: prom/prometheus:v2.11.1
  volumes:
   - ./data/prometheus.yml:/etc/prometheus/prometheus.yml
   - ./data/prometheus:/prometheus
  depends_on:
   - "pushgateway"
  command:
   - "--config.file=/etc/prometheus/prometheus.yml"
   - "--storage.tsdb.retention.time=2d"
  logging:
   options:
    max-size: 50m

 grafana:
  image: grafana/grafana
  restart: always
  environment:
   - GF_SECURITY_ADMIN_PASSWORD=enter
  depends_on:
   - prometheus
  volumes:
   - "./data/grafana:/var/lib/grafana"
   - "./data/grafana.ini:/etc/grafana/grafana.ini"
  logging:
   options:
    max-size: 50m

 manager:
  image: buckaroobanzay/minetest_manager
  restart: always
  volumes:
   - "./data:/data"
  environment:
   - WORLDMODS_DIR=/data/minetest/world/worldmods
   - WORLDMODS_BRANCH=master
   - MEDIADIR=/data/nginx/html/media
   - DEBUG_LOG=/data/minetest/debug.txt
   - ERROR_LOG_OUTPUT=/data/nginx/html/error-log.txt
  logging:
   options:
    max-size: 50m

 kv:
  image: anapsix/webdis
  restart: always
  environment:
   - LOCAL_REDIS=true

networks:
 terminator:
  external: true

 
